# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f7d32c29f7de82ccf48b99b460efef16"
name = "Shop-3D-APP"
handle = "shop-3d-app"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_products,write_files,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
