# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration


name = "Novaprint 3D Printing"
client_id = "7631acce31aefccf312387f3d5ab7286"
handle = "novaprint-3d-printing"
application_url = "https://integrated-organized-cal-gregory.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://integrated-organized-cal-gregory.trycloudflare.com/auth/callback", "https://integrated-organized-cal-gregory.trycloudflare.com/auth/shopify/callback", "https://integrated-organized-cal-gregory.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
